README.md

* Updates BibTeX with CoRL/arXiv paper information
* Tweaks to presentation and outline

Update README with CoRL paper

---

metaworld/envs/mujoco/mujoco_env.py
tests/helpers.py
tests/integration/test_memory_usage.py
tests/metaworld/envs/mujoco/sawyer_xyz/test_sawyer_parameterized.py

Fix gym.Env.close() implementation

---

metaworld/envs/mujoco/sawyer_xyz/sawyer_drawer_close.py

Fix goal position of drawer close environment #36 .

drawer_close bugfix

---

metaworld/benchmarks/ml10.py
metaworld/benchmarks/ml45.py
metaworld/benchmarks/mt10.py
metaworld/benchmarks/mt50.py
tests/metaworld/benchmarks/test_ml10.py
tests/metaworld/benchmarks/test_ml45.py
tests/metaworld/benchmarks/test_mt10.py
tests/metaworld/benchmarks/test_mt50.py

I'm not positive this is the most elegant solution, but it seems fine for now. We *should* be deleting this API soon anyways.

Fix setting random_init flags

---

metaworld/policies/action.py
metaworld/policies/policy.py
tests/metaworld/envs/mujoco/sawyer_xyz/utils.py

Per @avnishn's suggestion, separated base classes and utilities from policy implementations so that people have a clean slate to work from.

Base classes and utils for scripted policies

---

metaworld/envs/mujoco/env_dict.py
metaworld/envs/mujoco/sawyer_xyz/__init__.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_door_close_v2.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_door_v2.py

To solve the door-close env with scripted policies, I had to increase its `max_path_length` to 400.

Made door-close env solvable

---

metaworld/envs/mujoco/env_dict.py
metaworld/envs/mujoco/sawyer_xyz/__init__.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_peg_insertion_side_v2.py
metaworld/policies/__init__.py
metaworld/policies/policy.py
metaworld/policies/sawyer_peg_insertion_side_v2_policy.py
metaworld/policies/sawyer_peg_unplug_side_v1_policy.py
metaworld/policies/sawyer_window_close_v2_policy.py
metaworld/policies/sawyer_window_open_v2_policy.py
tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py

The peg-unplug env was fairly straightforward and solvable in V1. peg-insert was very broken so I added a V2 environment. Adjustments are listed in the changelog comment at the top of the class.
Success rates:
- peg-insert-v1: 0%
- peg-insert-v2: 96%
- peg-unplug-v1: 99%

Scripted policies for peg-insert and peg-unplug

---

metaworld/policies/__init__.py
metaworld/policies/sawyer_button_press_topdown_v1_policy.py
tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py

Success Rates:
- without noise: 100%
- with noise: 99%
Also:
- decreased `window-close-v1` success rate from 44% to 42%
- decreased `window-close-v2` success rate from 98% to 97%, as it was flaky before. Should close #109

Scripted policy for button-topdown environment

---

metaworld/envs/mujoco/env_dict.py
metaworld/envs/mujoco/sawyer_xyz/__init__.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_pick_place_v2.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_push_v2.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_reach_v2.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_shelf_place_v2.py
metaworld/policies/__init__.py
metaworld/policies/sawyer_shelf_place_v2_policy.py
setup.cfg
tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py

Scripted policy for Shelf place v2
Motivation for V2:
V1 was very difficult to solve because the observation doesn't reveal
where to move the block to (absolutely no information to reveal the
goal state).
Changelog from V1 to V2:
- (6/24/20) Added a 1 element vector to the observation. This vector
points along the x axis from the end effector to the goal's x
coordinate. i.e. (self._state_goal[0] - pos_hand[:0])
Minor policy edits:
edit change logs to use less strong language.

Shelf-Place V2 and minor policy edits

---

README.md
metaworld/__init__.py
tests/integration/test_new_api.py

I thought these were needed, but I was mistaken.

Remove test tasks from MT10 and MT50

---

metaworld/envs/assets_updated/sawyer_xyz/sawyer_assembly_peg.xml
metaworld/envs/mujoco/env_dict.py
metaworld/envs/mujoco/sawyer_xyz/__init__.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_assembly_peg_v2.py
metaworld/policies/__init__.py
metaworld/policies/sawyer_assembly_v2_policy.py
tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py

I had to change the `quat` property of the `RoundNut` XML (rotated 90 degrees relative to old XML) and update some magic numbers in the scripted policy, but otherwise this went smoothly. Policy success rate is the same.

Update assembly env to Byron's XML

---

MANIFEST.in

Reverts rlworkgroup/metaworld#230

Revert "Fix MANIFEST.in"

---

metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_push_v2.py
metaworld/policies/sawyer_push_v2_policy.py

The Push reward now works consistently to move the puck to the goal position. tensorboard: https://tensorboard.dev/experiment/6Wpku3QLTOSV6aMEjRg2Lw/
Check tag "exp3 -- push-v2"
I moved the gripper caging function to sawyer_xyz as well as removed some static constants from the function as they were not used anywhere else. this same function is also going to be used for sweep and sweep into.

New Push Reward

---

metaworld/envs/assets_v2/objects/assets/lever.xml
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_lever_pull_v2.py
metaworld/policies/sawyer_lever_pull_v2_policy.py

New reward function for lever pull

---

metaworld/envs/assets_v2/sawyer_xyz/sawyer_reach_v2.xml
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_reach_v2.py
metaworld/policies/sawyer_reach_v2_policy.py

* uses tolerance function
* updated xml to get access to quat values
* updated scripted policy to use new observation space.
This is a clean refactor of PR #245. check that PR for successful runs and tensorboard.

Update Reach-V2 with Successful Reward

---

metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_plate_slide_back_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_plate_slide_side_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_plate_slide_v2.py
metaworld/envs/reward_utils.py
metaworld/policies/sawyer_plate_slide_back_v2_policy.py
metaworld/policies/sawyer_plate_slide_side_v2_policy.py
metaworld/policies/sawyer_plate_slide_v2_policy.py

Successful Runs for Plate Slide: https://tensorboard.dev/experiment/7vNDhLVZTnGEJiWn576IpA/
Successful Runs for Plate Slide Back: https://tensorboard.dev/experiment/uXh465M0SaGSol9zdHKXeA
Successful Runs for Plate Slide Side: https://tensorboard.dev/experiment/aDyv8RQ1R4uVaLHkab4w6w/#scalars

New plate-slide, plate-slide-back, and plate-slide-side reward functions 

---

metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_door_v2.py
metaworld/envs/reward_utils.py
metaworld/policies/sawyer_door_open_v2_policy.py
tests/metaworld/envs/mujoco/sawyer_xyz/utils.py

https://tensorboard.dev/experiment/RzTA1r6rQAOxwJgfrsdO8g/

New reward function for door open

---

metaworld/envs/assets_v2/objects/assets/boxtop.xml
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_bin_picking_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_box_close_v2.py
metaworld/policies/sawyer_bin_picking_v2_policy.py
metaworld/policies/sawyer_box_close_v2_policy.py
scripts/plot_rewards_returns.ipynb

https://tensorboard.dev/experiment/J10Gl85PQMqvrqIJsELRGg/

New reward function for box close

---

metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_button_press_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_coffee_button_v2.py
metaworld/policies/sawyer_coffee_button_v2_policy.py

https://tensorboard.dev/experiment/3KiKcEDLS8KN0yAsjMBJiQ

New reward coffee button

---

metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_door_lock_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_door_unlock_v2.py
metaworld/policies/sawyer_door_lock_v2_policy.py
metaworld/policies/sawyer_door_unlock_v2_policy.py

New reward functions for lock and unlock

---

metaworld/envs/assets_v1/sawyer_xyz/sawyer_pick_place_wall_v2.xml
metaworld/envs/assets_v2/sawyer_xyz/sawyer_reach_wall_v2.xml
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_pick_place_wall_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_push_wall_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_reach_wall_v2.py
metaworld/policies/sawyer_pick_place_wall_v2_policy.py
metaworld/policies/sawyer_push_wall_v2_policy.py
metaworld/policies/sawyer_reach_wall_v2_policy.py

New reward functions and a few consistency fixes to the XMLs (They were changes I had wanted to do since the change to the V2 XMLs). All environments run on 3 successful seeds.

New Reach-Wall, Push-Wall, and Pick-Place-Wall reward functions

---

metaworld/envs/assets_v2/objects/assets/stick.xml
metaworld/envs/assets_v2/objects/assets/thermos.xml
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_stick_push_v2.py
metaworld/policies/sawyer_stick_push_v2_policy.py

New reward uses an extra site in order to better determine contact between stick and thermos
tensorboard: https://tensorboard.dev/experiment/UOCx6paoTmmI9OULn3zf1A

New stick push reward

---

metaworld/envs/assets_v2/sawyer_xyz/sawyer_coffee.xml
metaworld/envs/assets_v2/sawyer_xyz/sawyer_peg_unplug_side.xml
metaworld/envs/assets_v2/scene/basic_scene.xml
metaworld/envs/assets_v2/scene/basic_scene_wall.xml

Adds a retaining wall all the way around the table. File indentation also fixed.

Add retaining wall to v2 environments

---

metaworld/envs/assets_v2/objects/assets/handle_press.xml
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_handle_press_side_v2.py
metaworld/policies/sawyer_handle_press_side_v2_policy.py

Having issues with the handle staying upright after simulation starts

Handle press side reward

---

metaworld/envs/assets_v2/objects/assets/faucet.xml
metaworld/envs/assets_v2/sawyer_xyz/sawyer_faucet.xml
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_faucet_close_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_faucet_open_v2.py
metaworld/policies/sawyer_faucet_close_v2_policy.py
metaworld/policies/sawyer_faucet_open_v2_policy.py
tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py

These are the reward functions and updated xmls for
faucet open and faucet close.
Success rates @100 percent for both environments
closes #280 and addresses @haydenshively's comments

Faucet open and Faucet Close

---

metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_push_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_push_wall_v2.py

2 successful runs of push, 2 successful runs of push-wall.
Tensorboard: https://tensorboard.dev/experiment/9Ore6jieS7iKU02nkw2rkQ

Fixed Push Rewards to work with SAC

---

metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_push_v2.py

Fixing https://github.com/rlworkgroup/metaworld/issues/367

Fix slicing issue in push when random_init is False

---

Makefile
docker/Dockerfile
docker/entrypoint-headless.sh
metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
setup.py

Specify dtype for action, obs, and hand spaces

---

docker/Dockerfile
pyproject.toml
setup.py

Splitting https://github.com/Farama-Foundation/Metaworld/pull/414 into two separate PRs, this one is the minimal changes for pyproject.toml

Add pyproject.toml

---

docker/Dockerfile
metaworld/__init__.py
pyproject.toml
setup.py

This PR cleans up some minor typos and makes the project configuration all happen in pyproject.toml. 
CI has some issue which mean that dynamic versioning isn't currently possible, so I'm just gonna leave these changes which make things cleaner and fix typos.

Clean up setup.py() and set version in pyproject.toml

---

metaworld/__init__.py
metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py

Setup.toml does not install memory_profiler so this is an unnecessary import

removed unecessary import

---

docs/_static/metaworld-text.svg
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_coffee_push_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_plate_slide_back_side_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_plate_slide_back_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_plate_slide_side_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_plate_slide_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_reach_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_reach_wall_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_soccer_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_stick_pull_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_stick_push_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_sweep_into_goal_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_sweep_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_window_close_v2.py
metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_window_open_v2.py

there were some environments where the goal sphere (for rendering) wasn't updating correctly. This should fix the remaining environments

missing goal fixes

---

scripts/profile_memory_usage.py

I merged a commit for fixing the rendering of the gripper without asking them to fix pre-commit :)

fixing master ci
