Farama-Foundation/Metaworld

- MANIFEST.in
- README.md
Currently, the `pip install` does not copy over the assets in the final distribution and leads to the following error
Minimum example to reproduce
```python
from metaworld.benchmarks import ML1
env = ML1.get_train_tasks('pick-place-v1')
```
Error log
```
Traceback (most recent call last):
File "meta.py", line 2, in <module>
env = ML1.get_train_tasks('pick-place-v1')
File "/miniconda3/envs/lib/python3.7/site-packages/metaworld/benchmarks/ml1.py", line 41, in get_train_tasks
return cls(task_name, env_type='train', n_goals=50, sample_all=sample_all)
File "/miniconda3/envs/lib/python3.7/site-packages/metaworld/benchmarks/ml1.py", line 27, in __init__
sample_all=sample_all)
File "/miniconda3/envs/lib/python3.7/site-packages/metaworld/envs/mujoco/multitask_env.py", line 109, in __init_
_ …
```
> Fix missing assets after pip install

- metaworld/envs/mujoco/multitask_env.py
In MultiClassMultiTaskEnv, when `step` is called, the one hot encoding of the active env was not included in the returned `infos` dict. This PR addresses this issue by adding the one hot encoding to the returned env_info.
- By inheriting the parent class's step function
the one hot encoding of the environment is included
in the env_infos
> Fix missing one hot encoding in MultiClassMTEnv

- metaworld/envs/mujoco/multitask_env.py
- tests/metaworld/envs/test_multitask_env.py
This change is to improve the readability of task name.
* return the name of a task as it is designated in env_dict.py
* add `all_task_names()` that returns names of all available tasks.
> Expose names of all available tasks

- metaworld/envs/mujoco/__init__.py
The newest version of gym that installs with metaworld no longer has a tags field when environments are registered using the gym registration function.
We may need to pin the current version of gym and also remove the global registration of gym environments, but those things will be addressed in later PRs. @ryanjulian any input?
> Remove tags from registered envs

- metaworld/envs/mujoco/env_dict.py
- metaworld/envs/mujoco/multitask_env.py
- tests/metaworld/envs/test_multitask_env.py
* Ensure that static task ID is maintained.
After a call to discretize envs was made, the static task_id would be
ignored by the class, and task_envs would be assigned a new random task_id
Also addresses #71
* Make naming of envs standard across benchmarks
- removes some typos as well as ensures that envs have the same task name across benchmarks
* Addition of Static Task IDS
Addresses #68
- Adds static task ids for all metaworld envs to ensure
the ordering of envs is maintained regardless of python version
- Ensures that when envs are constructed using the from_task api
that they will always have the same task_id regardless of
how many other envs are constructed.
- Addition of tests for static task IDS and missing tests in
Multiclassmultitaskenv.py
> Static task ids

- metaworld/benchmarks/mt10.py
- metaworld/benchmarks/mt50.py
Added the from_task function to MT10 and MT50 so that users of those benchmarks can construct a single environment from the benchmark.
> Add from_task API for multitask benchmarks

- metaworld/envs/assets/sawyer_xyz/sawyer_pick_place_v2.xml
- metaworld/envs/assets/sawyer_xyz/sawyer_push_v2.xml
- metaworld/envs/assets/sawyer_xyz/sawyer_reach_v2.xml
- metaworld/envs/mujoco/env_dict.py
- metaworld/envs/mujoco/sawyer_xyz/__init__.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_pick_place_v2.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_push_v2.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_reach_v2.py
Originally, if env was randomized, it was basically unsolvable (The best strategy would be to randomly flail about, and hope to touch the `_state_goal` coordinate by luck).
_Options to fix were:_
- Add info about `_state_goal` to observation
- Keep `_state_goal` constant and instead have `random_init` impact the sawyer's starting position
I chose the first option. Specifically, the observation now includes a 3D vector that points from the end effector to `_state_goal`. @ryanjulian suggested just a euclidean distance, but as far as I can tell, that wouldn't provide enough information to solve the env in a stateless manner; the policy would have to guess and check for directionality. Hopefully my method doesn't count as goal conditioning.
> Made reach,push,pick-place env solvable

- metaworld/envs/mujoco/env_dict.py
- metaworld/envs/mujoco/sawyer_xyz/__init__.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_window_close_v2.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_window_open_v2.py
- metaworld/policies/__init__.py
- metaworld/policies/policy.py
- metaworld/policies/sawyer_window_close_v2_policy.py
- metaworld/policies/sawyer_window_open_v2_policy.py
- tests/integration/test_memory_usage.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_sawyer_parameterized.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py
- tests/metaworld/envs/mujoco/sawyer_xyz/utils.py
- tests/metaworld/envs/test_multitask_env.py
This PR adds scripted policies for the window-open and window-close environments. The policies achieve some success on v1 environments, but increasing `max_path_length` to 200 (see v2 envs) resulted in much higher success rates. I also addressed all of @ryanjulian's comments from #92, so ideally we would get this merged and then rebase the other scripted policies off of this.
> Scripted policies & V2 envs for window open/close

- setup.py
Correct me if I'm wrong, but as far as I can tell, we had absolutely no need for opencv and its only purpose was to vicariously obtain numpy.
> Remove opencv and add numpy

- MANIFEST.in
- setup.py
This is necessary to allow modern tools like poetry and pipenv to
install metaworld.
I have confirmed that the assets end up in the build directory, but I'm not 100% positive I did everything right. Having said that, everything seems to work.
> Replace MANIFEST.in with package_data

- metaworld/envs/mujoco/sawyer_xyz/sawyer_pick_place_v2.py
- metaworld/policies/__init__.py
- metaworld/policies/sawyer_pick_place_v2_policy.py
- metaworld/policies/sawyer_push_v2_policy.py
- metaworld/policies/sawyer_reach_v2_policy.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py
Hard-coded policies for the sawyer reach-push-pick-place environment. Since `random_init=True`, a test may fail occasionally, but that hasn't happened to me yet.
Note that these tests will fail on master, as the env is not solvable without changes from #95 
Partially addresses #90
> Scripted policies for reach-push-pick-place environment

- tests/integration/test_benchmarks.py
Disable integration tests due to failure from caused by glfw
from rendering. Will add back in after resolving docker ci issues.
> Temporarily disable large integration tests

- metaworld/envs/mujoco/sawyer_xyz/sawyer_basketball_v2.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_peg_insertion_side_v2.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_plate_slide_v2.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py
- tests/metaworld/envs/mujoco/sawyer_xyz/utils.py
Some V2 environments' observation spaces did not reflect the addition of new data to the observation.
This PR addresses this, and includes a test for this (likely needs to be relocated to its own individual test)
> Fix obs spaces of various V2 Environments

- README.md
In reference to #187. We should probably create a function that allows user to pass MTXX.train_tasks to it, and then returns dictionaries for constructors that would wrap the train tasks with a wrapper that augments the environments observations.
> Update README to modify description of task ids

- metaworld/envs/mujoco/sawyer_xyz/base.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py
- tests/metaworld/envs/mujoco/sawyer_xyz/utils.py
Re closes #39 
When being called via the ML1 wrapper, peg-insert-side still produces observations outside of its observation space, but all the other envs are now fixed. I have no idea why peg-insert-side is special, and it's fine if instantiated on its own (as far as I can tell).
> Fix obs spaces for partially observable tasks

- metaworld/envs/assets_v2/objects/assets/drawer.xml
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_drawer_open_v2.py
- metaworld/policies/sawyer_drawer_open_v2_policy.py
I based this on commit 0699efd8def2483760516babdb2064ba9feea745 since it looks like some stuff was accidentally committed after that without a PR.
Note that the reward could be fine-tuned to get rid of the humps/plateaus in the reward plot (for example by tracking leftpad position rather than gripper COM, or by using hamacher product of `XY<=thresh && Z` rather than my scaling factor hack), but we shouldn't have to do that. A high-entropy policy should explore past those and find it can achieve even higher reward.
Another option would be to scale the caging reward differently from the drawer-opening reward. For example `2 * caging + 8 * drawer_opening` rather than equal weighting.
Let me know if I need to implement any of this.
https://tensorboard.dev/experiment/1uKNBxnWQOydrEimYGxC2A/ …
> New reward function for drawer open

- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_peg_insertion_side_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_pick_place_v2.py
Make peg insertion and pick place high density
They were previously low density, however the initial new
mt10 runs revealed that grasps weren't able to completed with the
low density function and upon reruning peg insert with high density
it worked.
> Make peg insert pp high density

- metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_basketball_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_coffee_pull_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_hand_insert_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_peg_insertion_side_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_pick_place_wall_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_push_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_shelf_place_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_stick_push_v2.py
This is an alternative to the bug-fix that I posted previously. Rather than changing logic to match syntax, this changes syntax to match existing logic. That way we don't have to re-run experiments.
> Rename vars so that caging reward isn't a lie

- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_handle_pull_side_v2.py
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_handle_pull_v2.py
- metaworld/policies/sawyer_handle_pull_side_v2_policy.py
- metaworld/policies/sawyer_handle_pull_v2_policy.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py
- fix to handle pull side scripted policy (85 %)
- handle pull scripted policy currently doesn't work. I'm having issues with grasping the handle and then lifting it up.
- environments are trainable to 100 % success on 3 seeds in 3m timesteps or less with PPO
> Add obj radius to handle envs

- metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_sawyer_xyz_env.py
In some environments, the locations of objects are updated
via changes to the underlying simulator.
Those changes don't reflect in the simulator until the simulator
itself has been stepped (a call to sim.step()).
This commit forces sim.step when state rand vecs are changed by calling
reset inside set_task.
closes #324
> Force state rand vec updates to update the sim

- metaworld/envs/assets_v2/objects/assets/plug.xml
- metaworld/envs/assets_v2/sawyer_xyz/sawyer_peg_unplug_side.xml
- metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_peg_unplug_side_v2.py
- metaworld/policies/sawyer_peg_unplug_side_v2_policy.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_scripted_policies.py
New reward function for peg unplug side v2. Includes new grasp success parameter logic, and smooth rewards similar to all other new rewards.
Runs: 3/4 PPO (seeds: 1245, 2364, 9285_2, 6211<-failed seed) 3/3 SAC (seeds: 1374_1, 74542, 87643) 
Tensorboard: https://tensorboard.dev/experiment/mjVUMXn0S5iDKXUacbytxA/
> New Peg Unplug Side Reward

- metaworld/__init__.py
- metaworld/envs/mujoco/env_dict.py
Master was not using v2 environments in MT50 and ML45. 
env_dict still needs to be cleaned up a bit. 
@ryanjulian @tianheyu927:
Is it imperative that we give people to use the benchmark, and environments, in it's v1 version, from the metaworld package?
If not, I'd like to delete the v1 environments, and any additional code that came with them.
> Enable MT50 and ML45 constructors to use V2 envs

- metaworld/__init__.py
MT1 environment classes need to have distinct names otherwise users will have to treat their handling of multitask benchmarks such as MT10 and MT50 differently from how they handle MT1 environments.
> Give mt1 envs separate names

- metaworld/envs/mujoco/env_dict.py
- metaworld/envs/mujoco/mujoco_env.py
- metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
- tests/metaworld/envs/mujoco/sawyer_xyz/test_seeded_rand_vec.py
Currently when a `Benchmark` is created a set of `rand_vec` are chosen based on the seed passed into the `Benchmark` constructor, and then distributed among the `train_tasks` and `test_tasks`.
From then on, the only randomness in each environment is the initial state derived from those state objects.
However, several users (myself included) would also like to use individual environments with an unlimited number of initial states.
Currently, users achieve this by setting `env._freeze_rand_vec` to `False`, which causes the environment to sample from the global `np.random` state.
Although this results in a deterministic environment when used in Garage, many other RL frameworks do not, or cannot, make the global random state deterministic.
Unfortunately, the semantics of `_freeze_rand_vec` …
> Add an option to control rand_vec using a seed instead of the task

- .github/workflows/metaworld-ci.yml
Nightly CI is largely redundant with running the CI on pull requests, and it uses a lot of compute, so we should disable it.
> Disable nightly CI (CI on commit still runs)

- tests/metaworld/envs/mujoco/sawyer_xyz/test_sawyer_xyz_env.py
This change to CI changes the looseness of the "all_close" call when ensuring that observations are the same across environment resets. This is a logged issue (Issue #443) and will be dealt with accordingly. It's most likely due to changes in Mujoco bindings.
> Temporary fix for CI failing on `all_close` call checking repeated environment resets

- metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
in the previous version of Meta-World, there was a check to see if the current trajectory has equalled the maximum trajectory length. Now with environments returning termination and truncation signals, we can add a check to see if truncate should be sent by comparing the current trajectory length to the maximum trajectory length. To ensure that the environment does get reset, the ValueError that was normally raised hasn't been changed.
> Changing step to return truncate=True 

- metaworld/envs/assets_v2/sawyer_xyz/sawyer_basketball.xml
I found that the order to initialize mujoco bodies in the xml of the basketball v2 task is slightly different with others. This results in unexpected initial robot poses. An example is shown below:
In this function, the object is assumed to follow the robot qpos, however, in the xml for the basketball file, the order is inconsistent, which leads to unexpected initial pose of the robot.
https://github.com/Farama-Foundation/Metaworld/blob/87ac948c6f48475a962f9493cfdb8c338925cc74/metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py#L248-L254
In this pull request, I put the basketball behind the robot in the xml, and this issue seems to be resolved.
> Fixing qpos order in the xml of the basketball task.

- metaworld/envs/mujoco/sawyer_xyz/sawyer_xyz_env.py
- pyproject.toml
A key part missing from recent Metaworld renovation work is to stop depending on MuJoCo 2.X. Upgrading to MuJoCo 3.X opens up useful features such as:
- The ability to use MJX in the future
- The repository properly installing and working on latest macOS (MuJoCo 2's library path for OpenGL is wrong)
The main reason for not using MuJoCo 3.X before was that the benchmark did not work as intended and appeared to be broken (i.e. tests would fail).
Over the past few months, I did a deep dive on why this is and how to fix it. You can find a relatively in-depth documentation of the process and the findings in [this issue on the MuJoCo repo](https://github.com/google-deepmind/mujoco/issues/1483).
In the end I had to make a single change to get it working:
- Adjust the mocap weld constraint to …
> Update MuJoCo to 3.X

- metaworld/envs/assets_v2/objects/assets/xyz_base.xml
Fix the wrong rendering on the gripper FOV to a correct one.
Old position :
New position :
> Fix gripperFOV rendering

- README.md
- docs/introduction/basic_usage.md
- docs/rendering/rendering.md
- metaworld/assets/objects/assets/xyz_base.xml
**Description:**
This PR adds a new camera view named `corner4` to the Meta-World environments. The new camera provides an alternative perspective that can be used for rendering observations via the `camera_name` argument.
* Added `corner4` camera configuration to the relevant environments
* Updated camera registration (e.g., in `metaworld/envs/assets/sawyer_xyz/sawyer_xyz_env.py` or related camera logic)
* Verified compatibility with `gym.make_vec` API and multi-task setups
This new camera can now be used with the following instantiation:
```python
import gym
from metaworld.benchmark import MT10_V3
seed = 42
envs = gym.make_vec(
'Meta-World/custom-mt-envs', 
vector_strategy='sync', 
envs_list=[k for k in MT10_V3.keys()], 
width=256, height=256,
render_mode="rgb_array", …
```
> Add `corner4` camera to Meta-World environments
